include-pre-releases: true
prerelease-identifier: 'alpha'
tag-template: '$RESOLVED_VERSION'
name-template: '$RESOLVED_VERSION'
version-resolver:
  major:
    labels:
      - 'major'
      - breaking-change
  minor:
    labels:
      - 'minor'
      - 'enhancement'
      - 'feature'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'chore'
      - 'dependencies'
  default: patch
categories:
  - title: Breaking Changes 🛠
    labels:
      - breaking-change
  - title: 'New Features 🎉'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes 🛠'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'Documentation'
    labels:
      - 'docs'
  - title: 'Dependencies and extras 👒'
    collapse-after: 3
    labels:
      - 'chore'
      - 'dependencies'
exclude-labels:
  - 'ignore-for-release'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
autolabeler:
  - label: 'docs'
    branch:
      - '/docs{0,1}\/.+/'
  - label: 'chore'
    files:
      - '*.md'
      - '*.yml'
    branch:
      - '/chore\/.+/'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
      - '/feat\/.+/'
  - label: 'breaking-change'
    branch:
      - '/break\/.+/'
      - '/breaking\/.+/'
replacers:
  - search: '/CVE-(\d{4})-(\d+)/g'
    replace: 'https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-$1-$2'
template: |
  ## Changes

  $CHANGES
